In [ ]:
#Solution 1

In [ ]:
#A Python library is a collection of pre-written code and functions that extend the capabilities of Python. These libraries provide a wide range of functionalities and tools for various purposes, such as data analysis, machine learning, web development, scientific computing, and more.

 #why we use Python libraries:
  #      1.Reuse of code:
   #     2.Efficiency
    #    3.Specialized functionalities

In [ ]:
#Solution 2

In [ ]:
#NumPy arrays: All elements must be of the same data type (like all integers or all floats).
#Python lists: You can have mixed data types in the same list (like integers, floats, strings).

In [ ]:
#Solition 3

In [2]:
import numpy as np
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])


shape = array.shape
size = array.size
dimension = array.ndim

print("Shape:", shape)
print("Size:", size)
print("Dimension:", dimension)


Shape: (3, 4)
Size: 12
Dimension: 2


In [ ]:
#Solution 4

In [3]:
array = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]

first_row = array[0]
print(first_row)


[1, 2, 3, 4]


In [ ]:
#Solution 5

In [4]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

element = array[2, 3]
print(element)


12


In [ ]:
#Solution 6

In [5]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

odd_indexed_elements = array[:, 1::2]  
print(odd_indexed_elements)


[[ 2  4]
 [ 6  8]
 [10 12]]


In [ ]:
#Solution 7

In [6]:
import numpy as np

random_matrix = np.random.rand(3, 3)
print(random_matrix)


[[0.02638381 0.30442871 0.59660704]
 [0.62772773 0.0358603  0.1922432 ]
 [0.47452431 0.59420929 0.1912933 ]]


In [ ]:
#Solution 8

In [ ]:
#np.random.rand - it creates and array of specified shape and fills it with random values as per uniform distribution. values will be in [0,1)interval.
                                                                                                                                         
#np.random.randn -it creates and array of specified shape and fills it with random values as per standard normal distribution.                
                    

In [ ]:
#solution 9

In [7]:
import numpy as np
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
new_array = np.expand_dims(array, axis=0)

print(new_array)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [ ]:
#Solution 10

In [8]:
import numpy as np
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
transposed_array = np.transpose(array)
print(transposed_array)


[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
#Solution 11(1)

In [9]:
import numpy as np
A2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

B2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
result = A2 * B2

print(result)


[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [ ]:
#Solution 11(2)

In [10]:
import numpy as np
A2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

B2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
result = np.dot(A2, B2.T)  

print(result)


[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


In [ ]:
#solution11(3)

In [11]:
import numpy as np
A2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

B2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
add = A2+B2
print(add)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [ ]:
#Solution 11(4)

In [13]:
import numpy as np
A2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

B2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
subtract = A2-B2
print(subtract)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
#Solution 11(5)

In [14]:
import numpy as np
A2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

B2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
divide = B2/A2
print(divide)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#Solution 12

In [ ]:
#In NumPy use the byteswap() method to swap the byte order of an array.

In [ ]:
#Solution 13

In [ ]:
#The np.linalg.inv() function in NumPy is used to compute the inverse of a square matrix.

In [ ]:
#Solution 14

In [ ]:
#The np.reshape() function in NumPy is used to change the shape of an array without changing its data. It allows you to reorganize the elements of an array into a new shape, as long as the total number of elements remains the same.

In [ ]:
#Solution 15

In [ ]:
#Broadcasting is a fundamental concept in NumPy and is used extensively in array operations, mathematical functions, and more. Understanding broadcasting is essential for writing efficient and concise code when working with NumPy arrays.




